servicename: authorizing api
database:
  postgres:
    db: crenditals
    password: ButterFly777
    user: ivan
    port: 5432
    host: localhost
    sslmode: disable
    timezone: Asia/Shanghai
  redis:
    db: 0
    host: localhost
    port: 6379
    password: /home/ivan/Desktop/SP/secrets/.redis-password
logs:
  to:
    - stdin
    - ./logs/auth-%dd-mm-yy%.log # TODO: Elastic Search FileBeat Kibana Logstash
  format: JSON
  date: true
jwt:
  acsessttl: 30    #Minutes!
  refreshttl: 720  #Hours!
  signmethod: RS256
  audience:
    - "*.justnets.ru"
    - "*.devcomun.ru"
    - "*.everynumber.ru"
  issuer: JN Auth Service
  secret: /home/ivan/Desktop/SP/secrets/jwtRS256.key
  publickey: /home/ivan/Desktop/SP/secrets/jwtRS256.key.pub
router:
  port: 3000