version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 9920:9920
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ButterFly777
      POSTGRES_USER: ivan
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080